def menu():
    print("Fazer uma reserva")
    print("Editar reserva")
    print("Cancelar reserva")
    print("Ver todos os quartos reservados")
    print("Cadastrar quarto")
    print("Cadastrar cliente")
    print("Editar quarto")
    print("Editar cliente")
    print("Remover quarto")
    print("Remover cliente")
    print("Buscar quarto por número ou ID")
    print("Buscar cliente por nome ou ID")
    print("Sair")
    return input("Escolha uma opção: ")